"""add advice conversations and trading preferences"""

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone

revision = "ff1215287a55"
down_revision = "f22c50fdd6b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advice_conversations",
        sa.Column("stock_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advice_conversations_stock_id"), "advice_conversations", ["stock_id"], unique=False
    )
    op.create_table(
        "advice_messages",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("text", sa.String(length=30000), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("client_key", sa.String(length=100), nullable=True),
        sa.Column("reply_to_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["advice_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["advice_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "client_key"),
        sa.UniqueConstraint("reply_to_id"),
    )
    op.create_index(
        op.f("ix_advice_messages_conversation_id"), "advice_messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "trading_preferences",
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("quote", sa.String(length=1000), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["advice_messages.id"],
        ),
        sa.PrimaryKeyConstraint("field"),
    )
    # Initial preferences explicitly supplied in the user's project requirements.
    table = sa.table(
        "trading_preferences",
        sa.column("field", sa.String),
        sa.column("value", sa.String),
        sa.column("source", sa.String),
        sa.column("quote", sa.String),
        sa.column("confirmed", sa.Boolean),
        sa.column("locked", sa.Boolean),
        sa.column("updated_at", sa.String),
    )
    initial = [
        (
            "holding_period",
            "通常1—3个月；条件合适时可延长，最长7个月，需重新评估行情",
            "通常1-3月，如果行情允许，只要没有达到你的最高价格区间，如果余量还有10%以上，可以最大到7个月",
        ),
        (
            "trading_style",
            "稳健持有，不做快交易",
            "买卖风格以稳健，长期持有，在一个阶段的高点可以作为卖出点，不做快交易",
        ),
        ("exit_style", "关注阶段高点作为卖出参考", "在一个阶段的高点可以作为卖出点"),
    ]
    op.bulk_insert(
        table,
        [
            dict(
                field=field,
                value=value,
                quote=quote,
                source="project_brief",
                confirmed=True,
                locked=False,
                updated_at=datetime.now(timezone.utc).isoformat(),
            )
            for field, value, quote in initial
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trading_preferences")
    op.drop_index(op.f("ix_advice_messages_conversation_id"), table_name="advice_messages")
    op.drop_table("advice_messages")
    op.drop_index(op.f("ix_advice_conversations_stock_id"), table_name="advice_conversations")
    op.drop_table("advice_conversations")
    # ### end Alembic commands ###
